// Code generated by MockGen. DO NOT EDIT.
// Source: content.go

// Package content is a generated GoMock package.
package content

import (
	context "context"
	reflect "reflect"

	model "github.com/dmad1989/gophKeeper/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteContent mocks base method.
func (m *MockRepository) DeleteContent(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContent indicates an expected call of DeleteContent.
func (mr *MockRepositoryMockRecorder) DeleteContent(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContent", reflect.TypeOf((*MockRepository)(nil).DeleteContent), ctx, id)
}

// GetAllUserContent mocks base method.
func (m *MockRepository) GetAllUserContent(ctx context.Context) ([]*model.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserContent", ctx)
	ret0, _ := ret[0].([]*model.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserContent indicates an expected call of GetAllUserContent.
func (mr *MockRepositoryMockRecorder) GetAllUserContent(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserContent", reflect.TypeOf((*MockRepository)(nil).GetAllUserContent), ctx)
}

// GetUserContentByID mocks base method.
func (m *MockRepository) GetUserContentByID(ctx context.Context, id int32) (*model.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserContentByID", ctx, id)
	ret0, _ := ret[0].(*model.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserContentByID indicates an expected call of GetUserContentByID.
func (mr *MockRepositoryMockRecorder) GetUserContentByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserContentByID", reflect.TypeOf((*MockRepository)(nil).GetUserContentByID), ctx, id)
}

// GetUserContentByType mocks base method.
func (m *MockRepository) GetUserContentByType(ctx context.Context, t int32) ([]*model.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserContentByType", ctx, t)
	ret0, _ := ret[0].([]*model.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserContentByType indicates an expected call of GetUserContentByType.
func (mr *MockRepositoryMockRecorder) GetUserContentByType(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserContentByType", reflect.TypeOf((*MockRepository)(nil).GetUserContentByType), ctx, t)
}

// SaveContent mocks base method.
func (m *MockRepository) SaveContent(ctx context.Context, c model.Content) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveContent", ctx, c)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveContent indicates an expected call of SaveContent.
func (mr *MockRepositoryMockRecorder) SaveContent(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveContent", reflect.TypeOf((*MockRepository)(nil).SaveContent), ctx, c)
}

// UpdateContent mocks base method.
func (m *MockRepository) UpdateContent(ctx context.Context, c *model.Content) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContent", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContent indicates an expected call of UpdateContent.
func (mr *MockRepositoryMockRecorder) UpdateContent(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContent", reflect.TypeOf((*MockRepository)(nil).UpdateContent), ctx, c)
}
