// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Content struct {
	ID     int32
	UserID int32
	Type   int32
	Data   []byte
	Meta   pgtype.Text
}

type User struct {
	ID       int32
	Login    string
	Password []byte
}
