// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO public.users(login, password) 
VALUES ($1, $2)
RETURNING "ID"
`

type CreateUserParams struct {
	Login    string
	Password []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.Password)
	var ID int32
	err := row.Scan(&ID)
	return ID, err
}
