// Code generated by MockGen. DO NOT EDIT.
// Source: contents.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dmad1989/gophKeeper/pkg/model"
	enum "github.com/dmad1989/gophKeeper/pkg/model/enum"
	gomock "github.com/golang/mock/gomock"
)

// MockContentApp is a mock of ContentApp interface.
type MockContentApp struct {
	ctrl     *gomock.Controller
	recorder *MockContentAppMockRecorder
}

// MockContentAppMockRecorder is the mock recorder for MockContentApp.
type MockContentAppMockRecorder struct {
	mock *MockContentApp
}

// NewMockContentApp creates a new mock instance.
func NewMockContentApp(ctrl *gomock.Controller) *MockContentApp {
	mock := &MockContentApp{ctrl: ctrl}
	mock.recorder = &MockContentAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentApp) EXPECT() *MockContentAppMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockContentApp) Delete(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContentAppMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContentApp)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockContentApp) Get(ctx context.Context, id int32) (*model.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContentAppMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContentApp)(nil).Get), ctx, id)
}

// GetUserContent mocks base method.
func (m *MockContentApp) GetUserContent(ctx context.Context, typeID enum.ContentType) ([]*model.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserContent", ctx, typeID)
	ret0, _ := ret[0].([]*model.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserContent indicates an expected call of GetUserContent.
func (mr *MockContentAppMockRecorder) GetUserContent(ctx, typeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserContent", reflect.TypeOf((*MockContentApp)(nil).GetUserContent), ctx, typeID)
}

// Save mocks base method.
func (m *MockContentApp) Save(ctx context.Context, c *model.Content) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockContentAppMockRecorder) Save(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockContentApp)(nil).Save), ctx, c)
}

// Update mocks base method.
func (m *MockContentApp) Update(ctx context.Context, c *model.Content) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockContentAppMockRecorder) Update(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContentApp)(nil).Update), ctx, c)
}
